dist: trusty
group: deprecated-2017Q4
language: python
sudo: required
python:
    - "2.7"
services:
    - redis-server
    - postgresql
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
    - pip install codecov
after_success:
    - coveralls
